#! /usr/bin/ruby

require 'socket'
require 'uri'

class RGit

  def run(arguments)

    uri = getUri arguments[1]
    puts "protocol: #{uri.scheme} | host: #{uri.host} | port: #{uri.port} | path: #{uri.path}"

    socket = TCPSocket.new(uri.host, uri.port)

    output = "git-upload-pack #{uri.path}\0host=#{uri.host}\0"
    output = encode_packet_line(output)
    puts output

    socket.puts(output)

    while true
      lengthToken = socket.gets(4)
      length = lengthToken.to_i(16)
      break if length == 0
      response = socket.gets(length)
      puts response
    end

    socket.puts("0000")    
  end

  def getUri(text)

    uri = URI(text)
    uri.port = 9418 if uri.port == nil
    uri.path = "/" if uri.path == ""

    uri
  end

  def encode_packet_line(text)

    length = text.length + 4
    lengthToken = length.to_s(16).rjust(4, "0")

    output = lengthToken + text

    output
  end

end

RGit.new.run(ARGV)